-- Cláusula WHERE
SELECT * FROM EMPLOYEES E WHERE E.LAST_NAME = 'King';

-- WHERE com operadores de comparação
SELECT * FROM EMPLOYEES E WHERE E.SALARY >= 3000;

SELECT * FROM EMPLOYEES E WHERE E.SALARY <= 3000;

-- WHERE dentro de valores específicos
SELECT * FROM EMPLOYEES E WHERE E.SALARY BETWEEN 3000 AND 4000;

-- WHERE dentro de uma lista de valores
SELECT *
  FROM EMPLOYEES E
 WHERE E.JOB_ID IN ('IT_PROG', 'FI_ACCOUNT', 'SA_REP');

-- WHERE com coringa: % = seguidos de qualquer coisa. _ = apenas 1 caracter
SELECT * FROM EMPLOYEES E WHERE E.FIRST_NAME LIKE 'Sa%';

SELECT * FROM EMPLOYEES E WHERE E.FIRST_NAME LIKE '_a%';

-- ORDER BY
SELECT * FROM EMPLOYEES E ORDER BY E.HIRE_DATE DESC;

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY * 12 "SALÁRIO ANUAL" FROM EMPLOYEES E ORDER BY "SALÁRIO ANUAL" DESC;

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY * 12 "SALÁRIO ANUAL" FROM EMPLOYEES E ORDER BY 3 DESC;

-- Variáveis de substituição
SELECT * FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = &DEPARTMENT_ID; 

SELECT * FROM EMPLOYEES E WHERE E.JOB_ID = '&JOB_ID';

