-- View das time zones (somente DBA)
SELECT *
  FROM v$timezone_names tn
 WHERE REGEXP_LIKE(tn.tzname, 'Sao_Paulo');

-- SYSDATE
SELECT SYSDATE FROM DUAL;

-- SYSTIMESTAMP
SELECT SYSTIMESTAMP FROM DUAL;

-- INTERVAL YEAR TO MONTH
SELECT INTERVAL '55-11' YEAR TO MONTH FROM DUAL;

-- Funções (SYS)
-- Consultando a UTC do banco
SELECT DBTIMEZONE FROM DUAL;

-- Alterando a UTC do banco
ALTER DATABASE SET TIME_ZONE = '-03:00';

-- SESSIONTIMEZONE
SELECT SESSIONTIMEZONE FROM DUAL;

-- EXTRACT
SELECT EXTRACT(YEAR FROM SYSDATE) ANO,
       EXTRACT(MONTH FROM SYSDATE) MÊS,
       EXTRACT(DAY FROM SYSDATE) DIA
  FROM DUAL;
