-- SELECT mais básico que existe
SELECT E.* FROM EMPLOYEES E;

-- SELECT para exibir colunas específicas
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME FROM EMPLOYEES E;

-- SELECT com expressões aritméticas e utilizando o AS
SELECT E.FIRST_NAME NOME,
       E.LAST_NAME SOBRENOME,
       E.SALARY SALÁRIO,
       (E.SALARY * 1.15) "NOVO SALÁRIO"
  FROM EMPLOYEES E;

-- SELECT usando concatenação
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME "NOME DO FUNCIONÁRIO"
  FROM EMPLOYEES E;

-- SELECT com DISTINCT
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
