-- FLASHBACK VERSIONS QUERY - Privilégio a partir do SYS
GRANT EXECUTE ON DBMS_FLASHBACK TO KNELADEV;

-- Consultando o SCN atual
SELECT DBMS_FLASHBACK.get_system_change_number FROM DUAL;

-- Alterando a retenção do UNDO para 48 horas
ALTER SYSTEM SET UNDO_RETENTION = 172800;

-- SCN 17292603
DROP TABLE EMPLOYEES_COPY;
CREATE TABLE EMPLOYEES_COPY AS SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES_COPY E WHERE E.EMPLOYEE_ID = 170;

UPDATE EMPLOYEES_COPY E
   SET E.SALARY = E.SALARY * 2
 WHERE E.EMPLOYEE_ID = 170;

SELECT *
  FROM EMPLOYEES_COPY AS OF SCN 17292603
 WHERE EMPLOYEE_ID = 170;
